### ISSUE TITLE
Twitter card

### ISSUE THREAD

**Issue by IronRunes** [the-engine-room/2018-retro#4]

**Comment by lauraguzman** [comment]
Might pass this off to you @IronRunes once I get the final image!

**Comment by IronRunes** [comment]
Ok @lauraguzman , add a comment here when you upload the final image, then assign it to me. :)

**Comment by lauraguzman** [comment]
I actually think I updated it. If you’d like to double check (on Monday is fine), that’d be great. 

On Jan 6, 2019, at 4:20 AM, Alan Zard <notifications@github.com> wrote:

Ok @lauraguzman , add a comment here when you upload the final image, then assign it to me. :)

**Comment by IronRunes** [comment]
@lauraguzman all is working fine, you can check this stuff out at https://cards-dev.twitter.com/validator (thought it might turn out to be useful for you) 
WE ARE READY TO LAUNCH
